export const Users = [
    {
      id:1,
      profilePicture: "../../resources/picture/alex.jpg",
      username: "Patrick Ewing",
    },
    {
      id:2,
      profilePicture: "../../resources/picture/ami.jpg",
      username: "Denise Rodman",
    },
    {
      id:3,
      profilePicture: "../../resources/picture/bailey.jpg",
      username: "Nikola Jokic",
    },
    {
      id:4,
      profilePicture: "../../resources/picture/dima.jpg",
      username: "Gwen Rice",
    },
    {
      id:5,
      profilePicture: "../../resources/picture/Hsu.jpg",
      username: "Jamie Harden",
    },
    {
      id:6,
      profilePicture: "../../resources/picture/jake.jpg",
      username: "Andrea Wiggins",
    },
    {
      id:7,
      profilePicture: "../../resources/picture/jul.jpg",
      username: "Kevin Garnett",
    },
    {
      id:8,
      profilePicture: "../../resources/picture/lu.jpg",
      username: "Paula Pierce",
    },
    {
      id:9,
      profilePicture: "../../resources/picture/mat.jpg",
      username: "David Robinson",
    },
    {
      id:10,
      profilePicture: "../../resources/picture/mic.jpg",
      username: "Jamima O'Neal",
    },
  ];
  
  export const DummyPosts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "../../resources/images/IMG_10.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "../../resources/images/IMG_2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "../../resources/images/IMG_3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "../../resources/images/IMG_4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "../../resources/images/IMG_5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "../../resources/images/IMG_6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "../../resources/images/IMG_7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "../../resources/images/IMG_8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "../../resources/images/IMG_9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "../../resources/images/IMG_1.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];